# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f419f5b68e24eda2d6a52993e6721072bc3fe2a548bc325681e0bb9758cdcc6cf9e99c46e4d231e060122f21683fb0b3489d89a9413ff804d55c7fef184d9846

test:
  secret_key_base: eaf9a3f5514c222a511b476f0dfc486c4bf57e0e6d27ad73063907ef6e8a76e2d7cd30a88fc4244d8c006775feaf086a7146eb4718e5d2f329812577f49a2dd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
